# Generated by Django 3.2.5 on 2021-07-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.TextField(default='No Comment', max_length=100),
        ),
    ]
